    - name: Send Discord notification to Server 1
      env:
        DISCORD_WEBHOOK_ID: ${{ secrets.URC_WEBHOOK_ID }}
        DISCORD_WEBHOOK_TOKEN: ${{ secrets.URC_WEBHOOK_TOKEN }}
      run: |
        curl -v -X POST -H "Content-Type: application/json" -d "{\"content\": \"Static test message\"}" https://discord.com/api/webhooks/$URC_WEBHOOK_ID/$URC_WEBHOOK_TOKEN

