name: Send discord notification
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Prepare commit information
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an <%ae>")
        echo "Commit Message: $COMMIT_MESSAGE"
        echo "Commit Author: $COMMIT_AUTHOR"

    - name: Send Discord notification to Server 1
      env:
        DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
        DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      run: |
        COMMIT_URL="https://github.com/Unlimited-Research-Cooperative/Human-Brain-Rat/commits/${{ github.sha }}"
        JSON_PAYLOAD=$(jq -n \
                        --arg content "New commit by $COMMIT_AUTHOR! Check out the latest changes: $COMMIT_URL" \
                        --arg title "$COMMIT_MESSAGE" \
                        '{content: $content, embeds: [{title: $title}]}')
        echo "Payload: $JSON_PAYLOAD"
        curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://discord.com/api/webhooks/$DISCORD_WEBHOOK_ID/$DISCORD_WEBHOOK_TOKEN

    - name: Send Discord notification to Server 2
      env:
        URC_WEBHOOK_ID: ${{ secrets.URC_WEBHOOK_ID }}
        URC_WEBHOOK_TOKEN: ${{ secrets.URC_WEBHOOK_TOKEN }}
      run: |
        COMMIT_URL="https://github.com/Unlimited-Research-Cooperative/Human-Brain-Rat/commits/${{ github.sha }}"
        JSON_PAYLOAD=$(jq -n \
                        --arg content "New commit by $COMMIT_AUTHOR! Check out the latest changes: $COMMIT_URL" \
                        --arg title "$COMMIT_MESSAGE" \
                        '{content: $content, embeds: [{title: $title}]}')
        echo "Payload: $JSON_PAYLOAD"
        curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://discord.com/api/webhooks/$URC_WEBHOOK_ID/$URC_WEBHOOK_TOKEN

